config/routes.rb
Rails.application.routes.draw do
  root 'schools#index'

  resources :schools #the root and resources 'schools' needs to be the same as the contorllers tab that you call it
  
end

app/models/address.rb
class Address < ActiveRecord::Base
	belongs_to :school
end

app/models/classroom.rb
class Classroom < ActiveRecord::Base
	belongs_to :school
end

app/models/school.rb
class School < ActiveRecord::Base
	#dependent destroy will delete all the record that are associated
	#in the has/-many association---this is best practice
	has_many :classrooms, dependent: :destroy
	has_one :address, dependent: :destroy

	#validations go here
	#second line of defense for bad data--the first is the database contraint in the moigrate folder
	validates_presence_of :name
	#callbacks go here

	#you wont use these often- they are for more complicated situations

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/schools_controller.rb
class SchoolsController < ApplicationController
  def index
  	# GET--show all the schools
  	@schools = School.all
  end

  def show
  	#GET--show a specific school
  	@school = School.find(params[:id])
  end

  def edit
  	#GET--should hsow a form to edit a school
  	@school = School.find(params[:id])
  end

  def update
      @school = School.find(params[:id])
      if @school.update(school_params)
        redirect_to school_path
      else
        render :edit
      end
	end

  def new
  	#GET--should show a form to create a new school
  	@school =School.new
  end

  def create
  	#POST---creating a new school record in the database
  	@school = School.new(school_params)
  	if @school.save
  		redirect_to schools_path
  	else
  		render :new
  	end
  end

  def destroy
  	#method is responsible for deleting single school out of the database
		School.find(params[:id]).destroy
		redirect_to schools_path  
  end

  private

  def school_params
  	params.require(:school).permit(:name, :year_built)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/schools_helper.rb
module SchoolsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>DplRails</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/schools/_form.html.erb
<%= form_for @school do |f| %>
	<%= f.label :name %>
	<%= f.text_field :name %> 
	
	<%= f.label :year_built %>
	<%= f.text_field :year_built%>
	<%= f.submit %>
<%end%>

app/views/schools/edit.html.erb
<h1>Editing School: <%= @school.name %> </h1>
<br />

<%= render(partial: "form") %>

app/views/schools/index.html.erb
<h1>All schools</h1>
<br />

<!--what does the user see if ther are no schools?-->
<!--what does the user see if there are schools?-->
<!--add a link or a button to create  anew school-->	

<% if @schools.any? %>
	<!--loop the schools and diplay links to each one-->
	<ul>
		<% @schools.each do |school|%>
		  <li>
		    <%=link_to school.name, school_path(school)%>
		    <!-- <a href='/school/:id'>Neumont</a> is what the above link is doing-->
		  </li>
    <%end%>
  </ul>
<% else %>
  <h3>No schools found. PLease create one!</h3>
<%end%>

<%=link_to 'New School', new_school_path %>

app/views/schools/new.html.erb
<h1>Create a new school</h1>
<br/>

<%= render(partial: "form") %>

app/views/schools/show.html.erb
<h1><%= @school.name%> Info:</h1>
<br />
<h3>
	This school was built in: <%= @school.year_built %>
</h3>
<%= link_to 'All_schools', schools_path %>
<%= link_to 'Edit', edit_school_path %>
<%= link_to 'Delete', school_path, method: :delete %>